[package]
name = "photara"
version = "0.0.1"
edition = "2024"
description = "A photography workflow and publishing tool."
license = "MIT"
repository = "https://github.com/orbyts/photara"
homepage = "https://github.com/orbyts/photara"
readme = "README.md"
keywords = ["photography", "workflow", "lightroom", "publishing"]
categories = ["command-line-utilities"]

[dependencies]
storexa = "0.1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
