[package]
name = "photara-layout-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Built-in Layout node package for Photara."

[dependencies]
photara-core = { path = "../../crates/photara-core" }
photara-node-sdk = { path = "../../crates/photara-node-sdk" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
