[package]
name = "photara-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Persistence boundaries and adapters for Photara Core."

[dependencies]
photara-core = { path = "../photara-core" }
thiserror.workspace = true

[lints]
workspace = true
